### ISSUE TITLE
Occasional blank window on Ubuntu 18

### ISSUE THREAD

**Issue by fufesou** [rustdesk/rustdesk#2650]
**Describe the bug you encountered:**

The window is blank sometimes after app is started.

...

**What did you expect to happen instead?**

The window show normally.

...

**How did you install `RustDesk`?**

Github release.

---

**RustDesk version and environment**

Nightly build - 2022-12-26.  Ubuntu 18.04.

journalctl log:

```
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: Null check operator used on a null value
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #0      _PagePosition.applyViewportDimension (package:flutter/src/widgets/page_view.dart:455)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1456)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #15     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #16     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:552)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:579)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #21     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #22     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #23     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #25     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #26     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #27     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #28     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #33     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #35     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #37     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #38     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:552)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #39     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:579)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #74     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #78     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #86     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #87     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:552)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #88     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:579)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #98     RenderView.performLayout (package:flutter/src/rendering/view.dart:165)
Dec 20 05:01:02 ubuntu rustdesk.desktop[7343]: flutter: #99     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757)
```

**Comment by rustdesk** [comment]
Flutter 3.7.0 still has this problem?

**Comment by grummbeer** [comment]
related to #80
