### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by tkalevra** [rustdesk/rustdesk#4245]
### Bug Description

On following the installation instructions from Main I encountered a failure on build:
OS Details:
```
NAME="Zorin OS"
VERSION="16.2"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16.2"
VERSION_ID="16"
HOME_URL="https://zorin.com/os/"
SUPPORT_URL="https://help.zorin.com/"
BUG_REPORT_URL="https://zorin.com/os/feedback/"
PRIVACY_POLICY_URL="https://zorin.com/legal/privacy/"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
running as standard user the commands were successful until this one:
```
# VCPKG_ROOT=$HOME/vcpkg cargo run
```
which produced:
```
Compiling hyper-rustls v0.23.2
error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/rustdesk/magnum-opus#79be072c)`

Caused by:
  process didn't exit successfully: `/home/tmf/Documents/HelpDeskPro/004-RustDesk/rustdesk/rustdesk/target/debug/build/magnum-opus-7d6c6548bf024ede/build-script-build` (exit status: 101)
  --- stdout
  cargo:info=x64-linux
  cargo:rustc-link-lib=static=opus
  cargo:rustc-link-search=/root/vcpkg/installed/x64-linux/lib
  cargo:include=/root/vcpkg/installed/x64-linux/include
  rerun-if-changed=/root/.cargo/git/checkouts/magnum-opus-4bb999f3bcbf6ab0/79be072/opus_ffi.h
  rerun-if-changed=/root/vcpkg/installed/x64-linux/include

  --- stderr
  /root/.cargo/git/checkouts/magnum-opus-4bb999f3bcbf6ab0/79be072/opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found
  /root/.cargo/git/checkouts/magnum-opus-4bb999f3bcbf6ab0/79be072/opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /root/.cargo/git/checkouts/magnum-opus-4bb999f3bcbf6ab0/79be072/build.rs:128:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm unsure what other details would be required

### How to Reproduce

```
 2003  sudo apt install -y zip g++ gcc git curl wget nasm yasm libgtk-3-dev clang libxcb-randr0-dev libxdo-dev         libxfixes-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev libpulse-dev cmake make         libclang-dev ninja-build libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
 2004  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
 2005  source $HOME/.cargo/env
 2006  git clone https://github.com/rustdesk/rustdesk
 2007  cd rustdesk
 2008  mkdir -p target/debug
 2009  wget https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.lnx/x64/libsciter-gtk.so
 2010  mv libsciter-gtk.so target/debug
 2011  VCPKG_ROOT=$HOME/vcpkg cargo run
```

### Expected Behavior

Complete installation with working interface and communication between systems

### Operating system(s) on local side and remote side

zorinOS

### RustDesk Version(s) on local side and remote side

1.2.0

### Screenshots

```
   Compiling hyper-rustls v0.23.2
error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/rustdesk/magnum-opus#79be072c)`

Caused by:
  process didn't exit successfully: `/home/tmf/Documents/HelpDeskPro/004-RustDesk/rustdesk/rustdesk/target/debug/build/magnum-opus-7d6c6548bf024ede/build-script-build` (exit status: 101)
  --- stdout
  cargo:info=x64-linux
  cargo:rustc-link-lib=static=opus
  cargo:rustc-link-search=/root/vcpkg/installed/x64-linux/lib
  cargo:include=/root/vcpkg/installed/x64-linux/include
  rerun-if-changed=/root/.cargo/git/checkouts/magnum-opus-4bb999f3bcbf6ab0/79be072/opus_ffi.h
  rerun-if-changed=/root/vcpkg/installed/x64-linux/include

  --- stderr
  /root/.cargo/git/checkouts/magnum-opus-4bb999f3bcbf6ab0/79be072/opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found
  /root/.cargo/git/checkouts/magnum-opus-4bb999f3bcbf6ab0/79be072/opus_ffi.h:1:10: fatal error: 'opus/opus_multistream.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /root/.cargo/git/checkouts/magnum-opus-4bb999f3bcbf6ab0/79be072/build.rs:128:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by rustdesk** [comment]
#763
