### ISSUE TITLE
Build via Github Actions failing (Tag 1.23 and Nightly)

### ISSUE THREAD

**Issue by jacotec** [rustdesk/rustdesk#5966]
### Bug Description

I want to build the new version 1.23 with hardcoded server information as usual, unfortunately two jobs are failing:

![image](https://github.com/rustdesk/rustdesk/assets/3321655/77926ca0-09c7-49e8-8314-d5c868c484e0)

Unfortunately due to these dependencies only the Mac and Sciter versions are built:

![image](https://github.com/rustdesk/rustdesk/assets/3321655/edce4052-2395-4be6-b388-fcfa435f0a6f)

### How to Reproduce

Simply run the tag build for 1.23 or Nightly via GitHub actions

### Expected Behavior

It should run as before :)

### Operating system(s) on local side and remote side

 N/A

### RustDesk Version(s) on local side and remote side

N/A

### Screenshots

See above

### Additional Context

Log message for "generate_bridge":

```
2023/10/09 15:04:50 [INFO] Phase: Running build_runner
2023/10/09 15:04:50 [INFO] Running build_runner at /home/runner/work/rustdesk/rustdesk/./flutter
Unhandled exception:
Null check operator used on a null value
#0      PackageGraph.forPath.<anonymous closure> (package:build_runner_core/src/package_graph/package_graph.dart:106:72)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:3[44](https://github.com/jacotec/rustdesk/actions/runs/6458394497/job/17532013620#step:9:45):26)
#3      List.addAll (dart:core-patch/growable_array.dart:325:17)
#4      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:106:12)
<asynchronous suspension>
#5      main (file:///opt/hostedtoolcache/flutter/stable-3.10.6-x64/.pub-cache/hosted/pub.dev/build_runner-2.4.6/bin/build_runner.dart:27:30)
<asynchronous suspension>
2023/10/09 15:05:02 [WARN] command=cd "/home/runner/work/rustdesk/rustdesk/./flutter" && "sh" "-c" "\"flutter\" \"pub\" \"run\" \"build_runner\" \"build\" \"--delete-conflicting-outputs\"" stdout= stderr=
Error: /09 15:05:02 [ERROR] fatal: Failed to run build_runner for /home/runner/work/rustdesk/rustdesk/./flutter: 
Error: Process completed with exit code 1.

```

Log message for "x86_64-pc-windows-msvc (windows-2019)"

```
2023/10/09 15:10:50 [INFO] Phase: Running build_runner
2023/10/09 15:10:50 [INFO] Running build_runner at D:\a\rustdesk\rustdesk\./flutter
Unhandled exception:
Null check operator used on a null value
#0      PackageGraph.forPath.<anonymous closure> (package:build_runner_core/src/package_graph/package_graph.dart:106:72)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#3      List.addAll (dart:core-patch/growable_array.dart:325:17)
#4      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:106:12)
<asynchronous suspension>
#5      main (file:///C:/hostedtoolcache/windows/flutter/stable-3.10.6-x64/.pub-cache/hosted/pub.dev/build_runner-2.4.6/bin/build_runner.dart:27:30)
<asynchronous suspension>
2023/10/09 15:11:07 [WARN] command="powershell" "-noprofile" "-command" "& \"flutter\" \"pub\" \"run\" \"build_runner\" \"build\" \"--delete-conflicting-outputs\"" stdout= stderr=
Error: /09 15:11:07 [ERROR] fatal: Failed to run build_runner for D:\a\rustdesk\rustdesk\./flutter: 
Error: Process completed with exit code 1.

```

**Comment by rustdesk** [comment]
#763

**Comment by jacotec** [comment]
@rustdesk That does not help as a supported build procedure via GitHub actions, set up via official docs, broke with 1.23 ...
So it's not a custom setup, it's the official way with the official GitHub actions.
