### ISSUE TITLE
Android build fail

### ISSUE THREAD

**Issue by CListery** [rustdesk/rustdesk#755]
```log
VCPKG_ROOT=$HOME/work/rustdesk/vcpkg ANDROID_NDK_HOME=$HOME/work/rustdesk/android-ndk-r22b flutter/ndk_arm64.sh

[2022-06-13T08:31:39Z INFO  cargo_ndk::cli] Using NDK at path: /home/cyh/work/rustdesk/android-ndk-r22b
[2022-06-13T08:31:39Z INFO  cargo_ndk::cli] NDK API level: 21
[2022-06-13T08:31:39Z INFO  cargo_ndk::cli] Building targets: arm64-v8a
[2022-06-13T08:31:39Z INFO  cargo_ndk::cli] Building arm64-v8a (aarch64-linux-android)
   Compiling hbb_common v0.1.0 (/home/cyh/work/rustdesk/rustdesk/libs/hbb_common)
   Compiling magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86)
   Compiling scrap v0.5.0 (/home/cyh/work/rustdesk/rustdesk/libs/scrap)
error: failed to run custom build command for `scrap v0.5.0 (/home/cyh/work/rustdesk/rustdesk/libs/scrap)`

Caused by:
  process didn't exit successfully: `/home/cyh/work/rustdesk/rustdesk/target/release/build/scrap-89ab3dddac6f89ef/build-script-build` (exit status: 101)
  --- stdout
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=yuv
  cargo:rustc-link-search=/home/cyh/work/rustdesk/vcpkg/installed/arm64-android/lib
  cargo:include=/home/cyh/work/rustdesk/vcpkg/installed/arm64-android/include
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=vpx
  cargo:rustc-link-search=/home/cyh/work/rustdesk/vcpkg/installed/arm64-android/lib
  cargo:include=/home/cyh/work/rustdesk/vcpkg/installed/arm64-android/include
  rerun-if-changed=/home/cyh/work/rustdesk/rustdesk/libs/scrap/vpx_ffi.h
  rerun-if-changed=/home/cyh/work/rustdesk/vcpkg/installed/arm64-android/include

  --- stderr
  /usr/include/features-time64.h:20:10: fatal error: 'bits/wordsize.h' file not found
  /usr/include/features-time64.h:20:10: fatal error: 'bits/wordsize.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libs/scrap/build.rs:63:18
  stack backtrace:
     0:     0x563f0d58878d - std::backtrace_rs::backtrace::libunwind::trace::he7b2256f11b219c4
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x563f0d58878d - std::backtrace_rs::backtrace::trace_unsynchronized::h5940026febc37896
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x563f0d58878d - std::sys_common::backtrace::_print_fmt::hace3d716a44d00be
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x563f0d58878d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he585d9ce3c59d10a
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x563f0d5ae00c - core::fmt::write::h0bc2ae81eb1fce1c
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/core/src/fmt/mod.rs:1196:17
     5:     0x563f0d585451 - std::io::Write::write_fmt::h6fadb67a76056233
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/io/mod.rs:1654:15
     6:     0x563f0d589f15 - std::sys_common::backtrace::_print::h2ea63a82404cc437
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x563f0d589f15 - std::sys_common::backtrace::print::h6b3a52fed0fad2f9
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x563f0d589f15 - std::panicking::default_hook::{{closure}}::h6a426a6042322a8f
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:295:22
     9:     0x563f0d589c36 - std::panicking::default_hook::hccc6c0c96e1bf987
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:314:9
    10:     0x563f0d58a4a6 - std::panicking::rust_panic_with_hook::h3f7e1f19ad891624
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:698:17
    11:     0x563f0d58a397 - std::panicking::begin_panic_handler::{{closure}}::h9a7e045e85e0ed24
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:588:13
    12:     0x563f0d588c44 - std::sys_common::backtrace::__rust_end_short_backtrace::hd77c30739daac554
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x563f0d58a0c9 - rust_begin_unwind
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:584:5
    14:     0x563f0d0b6f13 - core::panicking::panic_fmt::h9d76f7ef55ba0936
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/core/src/panicking.rs:142:14
    15:     0x563f0d0b7003 - core::result::unwrap_failed::h83edea5f763e726f
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/core/src/result.rs:1805:5
    16:     0x563f0d0ba883 - core::result::Result<T,E>::unwrap::hd4821e9a8c3139f5
    17:     0x563f0d0b86e9 - build_script_build::generate_bindings::h41049343efccff56
    18:     0x563f0d0b8e3f - build_script_build::gen_vpx::h184aa89d3559af66
    19:     0x563f0d0b900f - build_script_build::main::hc906e27e2e929b12
    20:     0x563f0d0b98c3 - core::ops::function::FnOnce::call_once::h77bbdd314de51623
    21:     0x563f0d0ba379 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc643375b9205b36e
    22:     0x563f0d0b9bc9 - std::rt::lang_start::{{closure}}::h79fb75e934bd8637
    23:     0x563f0d58117e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hacca0318722d0dfc
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/core/src/ops/function.rs:280:13
    24:     0x563f0d58117e - std::panicking::try::do_call::h2ee20a7b0a2114e4
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:492:40
    25:     0x563f0d58117e - std::panicking::try::hbfe9cd18aeb87f0a
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:456:19
    26:     0x563f0d58117e - std::panic::catch_unwind::h96fc7bef42dc04ea
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panic.rs:137:14
    27:     0x563f0d58117e - std::rt::lang_start_internal::{{closure}}::h3e67d097ffae184c
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/rt.rs:128:48
    28:     0x563f0d58117e - std::panicking::try::do_call::hbfa18b72284cab71
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:492:40
    29:     0x563f0d58117e - std::panicking::try::h3cc183f58e9de21e
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:456:19
    30:     0x563f0d58117e - std::panic::catch_unwind::h715961407b2dd861
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panic.rs:137:14
    31:     0x563f0d58117e - std::rt::lang_start_internal::hc01b6af4323b03cc
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/rt.rs:128:20
    32:     0x563f0d0b9bb1 - std::rt::lang_start::h36688f8925659ad6
    33:     0x563f0d0b9163 - main
    34:     0x7f7b70a0cd90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    35:     0x7f7b70a0ce40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    36:     0x563f0d0b7205 - _start
    37:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86)`

Caused by:
  process didn't exit successfully: `/home/cyh/work/rustdesk/rustdesk/target/release/build/magnum-opus-a48cc3007a54084b/build-script-build` (exit status: 101)
  --- stdout
  cargo:info=arm64-android
  cargo:rustc-link-lib=static=opus
  cargo:rustc-link-search=/home/cyh/work/rustdesk/vcpkg/installed/arm64-android/lib
  cargo:include=/home/cyh/work/rustdesk/vcpkg/installed/arm64-android/include
  rerun-if-changed=/home/cyh/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/opus_ffi.h
  rerun-if-changed=/home/cyh/work/rustdesk/vcpkg/installed/arm64-android/include

  --- stderr
  /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
  /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/cyh/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/build.rs:66:18
  stack backtrace:
     0:     0x5571d722e0ad - std::backtrace_rs::backtrace::libunwind::trace::he7b2256f11b219c4
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x5571d722e0ad - std::backtrace_rs::backtrace::trace_unsynchronized::h5940026febc37896
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5571d722e0ad - std::sys_common::backtrace::_print_fmt::hace3d716a44d00be
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x5571d722e0ad - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he585d9ce3c59d10a
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x5571d725329c - core::fmt::write::h0bc2ae81eb1fce1c
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/core/src/fmt/mod.rs:1196:17
     5:     0x5571d722ad71 - std::io::Write::write_fmt::h6fadb67a76056233
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/io/mod.rs:1654:15
     6:     0x5571d722f835 - std::sys_common::backtrace::_print::h2ea63a82404cc437
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x5571d722f835 - std::sys_common::backtrace::print::h6b3a52fed0fad2f9
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x5571d722f835 - std::panicking::default_hook::{{closure}}::h6a426a6042322a8f
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:295:22
     9:     0x5571d722f556 - std::panicking::default_hook::hccc6c0c96e1bf987
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:314:9
    10:     0x5571d722fdc6 - std::panicking::rust_panic_with_hook::h3f7e1f19ad891624
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:698:17
    11:     0x5571d722fcb7 - std::panicking::begin_panic_handler::{{closure}}::h9a7e045e85e0ed24
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:588:13
    12:     0x5571d722e564 - std::sys_common::backtrace::__rust_end_short_backtrace::hd77c30739daac554
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x5571d722f9e9 - rust_begin_unwind
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:584:5
    14:     0x5571d6d84e13 - core::panicking::panic_fmt::h9d76f7ef55ba0936
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/core/src/panicking.rs:142:14
    15:     0x5571d6d84f03 - core::result::unwrap_failed::h83edea5f763e726f
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/core/src/result.rs:1805:5
    16:     0x5571d6d89c93 - core::result::Result<T,E>::unwrap::h4551e4522d773779
    17:     0x5571d6d8667e - build_script_build::generate_bindings::h805be8d30a607bc5
    18:     0x5571d6d86cc6 - build_script_build::gen_opus::hed00fef1c37b36e9
    19:     0x5571d6d86d56 - build_script_build::main::h948523a0af933921
    20:     0x5571d6d89473 - core::ops::function::FnOnce::call_once::h83cd17ce78f79f4a
    21:     0x5571d6d87409 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7311ba61dc22705a
    22:     0x5571d6d89429 - std::rt::lang_start::{{closure}}::h6f624b7709aafd00
    23:     0x5571d7226e9e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hacca0318722d0dfc
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/core/src/ops/function.rs:280:13
    24:     0x5571d7226e9e - std::panicking::try::do_call::h2ee20a7b0a2114e4
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:492:40
    25:     0x5571d7226e9e - std::panicking::try::hbfe9cd18aeb87f0a
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:456:19
    26:     0x5571d7226e9e - std::panic::catch_unwind::h96fc7bef42dc04ea
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panic.rs:137:14
    27:     0x5571d7226e9e - std::rt::lang_start_internal::{{closure}}::h3e67d097ffae184c
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/rt.rs:128:48
    28:     0x5571d7226e9e - std::panicking::try::do_call::hbfa18b72284cab71
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:492:40
    29:     0x5571d7226e9e - std::panicking::try::h3cc183f58e9de21e
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panicking.rs:456:19
    30:     0x5571d7226e9e - std::panic::catch_unwind::h715961407b2dd861
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/panic.rs:137:14
    31:     0x5571d7226e9e - std::rt::lang_start_internal::hc01b6af4323b03cc
                                 at /rustc/546c826f0ccaab36e897860205281f490db274e6/library/std/src/rt.rs:128:20
    32:     0x5571d6d89411 - std::rt::lang_start::hafabecefe675ce47
    33:     0x5571d6d86db3 - main
    34:     0x7f0fd14ebd90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    35:     0x7f0fd14ebe40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    36:     0x5571d6d85105 - _start
    37:                0x0 - <unknown>
warning: unreachable expression
   --> libs/hbb_common/src/config.rs:270:9
    |
269 |           return Self::path(APP_HOME_DIR.read().unwrap().as_str());
    |           -------------------------------------------------------- any code following this expression is unreachable
270 | /         if let Some(path) = dirs_next::home_dir() {
271 | |             patch(path)
272 | |         } else if let Ok(path) = std::env::current_dir() {
273 | |             path
274 | |         } else {
275 | |             std::env::temp_dir()
276 | |         }
    | |_________^ unreachable expression
    |
    = note: `#[warn(unreachable_code)]` on by default

warning: unreachable statement
   --> libs/hbb_common/src/config.rs:287:9
    |
284 |             return path;
    |             ----------- any code following this expression is unreachable
...
287 |         let org = "";
    |         ^^^^^^^^^^^^^ unreachable statement

warning: unreachable statement
   --> libs/hbb_common/src/config.rs:475:9
    |
469 | /             return Some(
470 | |                 rand::thread_rng()
471 | |                     .gen_range(1_000_000_000..2_000_000_000)
472 | |                     .to_string(),
473 | |             );
    | |_____________- any code following this expression is unreachable
474 |           }
475 |           let mut id = 0u32;
    |           ^^^^^^^^^^^^^^^^^^ unreachable statement

warning: unused variable: `id`
   --> libs/hbb_common/src/config.rs:475:17
    |
475 |         let mut id = 0u32;
    |                 ^^ help: if this is intentional, prefix it with an underscore: `_id`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `hbb_common` (lib) generated 4 warnings
[2022-06-13T08:32:08Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2022-06-13T08:32:08Z INFO  cargo_ndk::cli] 
[2022-06-13T08:32:08Z INFO  cargo_ndk::cli]     rustup target install aarch64-linux-android

```

**Comment by davistsin** [comment]
```shell
cd 
git clone https://github.com/microsoft/vcpkg
cd vcpkg
./bootstrap-vcpkg.sh
brew install nasm yasm
./vcpkg install libvpx libyuv opus --triplet arm64-android
```
