### ISSUE TITLE
Can't connect to Windows Client

### ISSUE THREAD

**Issue by twprh** [rustdesk/rustdesk#8006]
### Bug Description

No connection possilble

### How to Reproduce

just try to connect (from linux to windows)

### Expected Behavior

same behavior as past versions (nightly 1-2 days ago work ok)

### Operating system(s) on local side and remote side

Linux Mint   -> Windows

### RustDesk Version(s) on local side and remote side

both last nightly from 240509

### Screenshots

![grafik](https://github.com/rustdesk/rustdesk/assets/46543715/34e4307e-7ebc-4b75-8b27-4abc41db120a)

### Additional Context

```
user@user-TW8-SW8-DW8 ~ $ rustdesk
Cannot load libcuda.so.1
Cannot load libcuda.so.1
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:0123456789012345678901234567899f,info2-name:Linux Mint,dir:/home/user/Dokumente
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: pullAb, force: ForcePullAb.listAndCurrent, quiet: false
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: restore lpos: 800.0/600.0, offset:54.0/16.0
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: {0}
flutter: [MultiWindowHandler] active window changed: {0, 1}
flutter: launch args: [multi_window, 1, {"type":1,"id":"0123456789","password":"","forceRelay":false,"isSharedPassword":false}]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_ffiBind@1082203822' has not been initialized.
#0      new StateGlobal._ (package:flutter_hbb/models/state_model.dart)
#1      StateGlobal.instance (package:flutter_hbb/models/state_model.dart:113)
#2      stateGlobal (package:flutter_hbb/models/state_model.dart)
#3      main (package:flutter_hbb/main.dart)
#4      _runMain.<anonymous closure> (dart:ui/hooks.dart:299)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method new_remote_desktop on channel mixin.one/flutter_multi_window_channel)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      RustDeskMultiWindowManager.call (package:flutter_hbb/utils/multi_window_manager.dart:288)
<asynchronous suspension>
#2      RustDeskMultiWindowManager.newRemoteDesktop (package:flutter_hbb/utils/multi_window_manager.dart:240)
<asynchronous suspension>
#3      connectMainDesktop (package:flutter_hbb/common.dart:2133)
<asynchronous suspension>
#4      connect (package:flutter_hbb/common.dart:2173)
<asynchronous suspension>

flutter: [MultiWindowHandler] active window changed: {1}

```

**Comment by rustdesk** [comment]
please help tell us build datetime.

**Comment by twprh** [comment]
Version: 1.2.4
Builddate: 2024-05-10 02:55

**Comment by rustdesk** [comment]
Try current nightly, it has been fixed.

**Comment by twprh** [comment]
:+1: thanks for fast fix
