### ISSUE TITLE
Raspberry PI 4 with Ubuntu ARM64

### ISSUE THREAD

**Issue by Darkyere** [rustdesk/rustdesk#853]
I would like to request an ARM64 build for RPI4 with ubuntu.

Currently if i try to install the [rustdesk-1.1.9-raspberry-armhf.deb](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-raspberry-armhf.deb) i have to install 18.4 GB of data.

That seems like a bit to much to pull down tbh 

And the [rustdesk-1.1.9.deb](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb) is for AMD64 only.

Hope this request is possible,
and thnk you for reading.

Best Regards,
Darkyere

**Comment by rustdesk** [comment]
sciter has no 64 bit version yet. we have to wait for our migration to flutter desktop.

**Comment by Darkyere** [comment]
Thank you for the info.

I am just curious, i dont need it right away.

But when are u moving to flutter?
And what will it mean for currently already installed server and Clients on Linux/MAC/Windows machines?

**Comment by knro** [comment]
> sciter has no 64 bit version yet. we have to wait for our migration to flutter desktop.

There is an [arm64 version now](https://github.com/c-smile/sciter-sdk/issues/210). Is there anything else blocking Raspberry PI bullseye arm64 build for RustDesk now?

**Comment by rustdesk** [comment]
That's js sdk, but we are using tis sdk.

**Comment by knro** [comment]
> That's js sdk, but we are using tis sdk.

Sorry I'm not following, where is tis sdk? where can we ask about this?

**Comment by Heap-Hop** [comment]
@knro 

> That's js sdk, but we are using tis sdk.

Sadly, we can't build again.

**Comment by knro** [comment]
@rustdesk They just released [arm64 Linux binaries](https://github.com/c-smile/sciter-sdk/tree/master/bin.lnx/arm64). This clears the way now for arm64 Linux build of Rustdesk?

**Comment by Heap-Hop** [comment]
I built rustdesk arm64, but unfortunately it crashed without clear log. I will try to fix it sometine (low priority). 
Contributions are welcome!

**Comment by knro** [comment]
@Heap-Hop Glad to help, where is the built binary? Can rust be debugged in gdb?

**Comment by Heap-Hop** [comment]
@knro  Thanks, you can build it in your device, see:
https://github.com/rustdesk/rustdesk/discussions/697#discussioncomment-2879261
https://github.com/rustdesk/rustdesk#how-to-build-on-linux

Both `apt` and `vcpkg` could fetch `libvpx` and `libopus`.
And build libyuv manually:
```
git clone https://chromium.googlesource.com/libyuv/libyuv/

cd libyuv

make -f linux.mk

# cp libyuv.a and include to $VCPKG_ROOT/installed/arm64-linux
```

**Comment by knro** [comment]
When I execute cargo run, I get this:
```
error: failed to parse manifest at `/home/jasem/rustdesk/Cargo.toml`
Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`

```

**Comment by knro** [comment]
I installed a newer version of Cargo, but then got these errors during compiling:

```
Compiling libsodium-sys v0.2.7
   Compiling magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86)
   Compiling scrap v0.5.0 (/home/jasem/binaries/rustdesk/libs/scrap)
error: failed to run custom build command for `scrap v0.5.0 (/home/jasem/binaries/rustdesk/libs/scrap)`

Caused by:
  process didn't exit successfully: `/home/jasem/binaries/rustdesk/target/debug/build/scrap-8438ab660e105344/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', libs/scrap/build.rs:7:50
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
     2: core::result::unwrap_failed
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1078:23
     4: build_script_build::find_package
               at ./build.rs:7:22
     5: build_script_build::main
               at ./build.rs:97:5
     6: core::ops::function::FnOnce::call_once
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86)`

Caused by:
  process didn't exit successfully: `/home/jasem/binaries/rustdesk/target/debug/build/magnum-opus-fdb32359fc700b9a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /home/jasem/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/build.rs:7:50
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
     2: core::result::unwrap_failed
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1078:23
     4: build_script_build::find_package
               at ./build.rs:7:22
     5: build_script_build::gen_opus
               at ./build.rs:70:20
     6: build_script_build::main
               at ./build.rs:87:5
     7: core::ops::function::FnOnce::call_once
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by knro** [comment]
@rustdesk @Heap-Hop Is there any thing I can do to move this forward? Not sure what to do next.

**Comment by rustdesk** [comment]
Thanks for your effort. Hope you can solve compilation problem yourself. We have to move forward our project rather than pause here.

**Comment by knro** [comment]
@rustdesk Thanks, I was hoping for an official arm64 release by Rustdesk. Many embedded devices moved to arm64 by default now.

**Comment by rustdesk** [comment]
Soon or later, but you need to wait.

**Comment by rustdesk** [comment]
Wait for this.
https://github.com/rustdesk/rustdesk/discussions/918

**Comment by knro** [comment]
Thanks, can you clarify what this means exactly? do we have arm64 version now? or we will after flutter desktop branch is merged to main?

**Comment by zlaazlaa** [comment]
I try to install [rustdesk-1.1.9-raspberry-armhf.deb](https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-raspberry-armhf.deb) on [Ubuntu for Raspberry Pi](https://ubuntu.com/download/raspberry-pi/thank-you?version=22.04.1&architecture=desktop-arm64+raspi), but failed. 
Could you tell me does rustdesk support the arm system perfectly now?

**Comment by rustdesk** [comment]
https://github.com/microsoft/vcpkg/issues/27281

**Comment by Darkyere** [comment]
I wanted to do some more testing than what i did initially.

So when i visited my parents today I installed the pkg.tar version on my Arch Linux install.

And tried to connect.
I get an disconnected by peer issue.

So i thought it might be an issue with the arch version.

So went on their W10 PC and ran the RustDesk 1.2 an tried connecting again.
Reset by peer again.

I tried restarting the RustDesk service on the RPI4.

But i could't make it work.

Is there anything in particular i need to do to trouble shoot the issue ?

**Comment by Kingtous** [comment]
> I wanted to do some more testing than what i did initially.
> 
> So when i visited my parents today I installed the pkg.tar version on my Arch Linux install.
> 
> And tried to connect.
> I get an disconnected by peer issue.
> 
> So i thought it might be an issue with the arch version.
> 
> So went on their W10 PC and ran the RustDesk 1.2 an tried connecting again.
> Reset by peer again.
> 
> I tried restarting the RustDesk service on the RPI4.
> 
> But i could't make it work.
> 
> Is there anything in particular i need to do to trouble shoot the issue ?

seems like a connection issue? relay or something? @rustdesk

**Comment by Kingtous** [comment]
> I have installed and tested the RustDesk Nightly 1.2 from 2022-11-28,
> on my RPI4 8GB with Ubuntu 22.04.1 ARM64.
> 
> And it seems to function properly. 
> 
> I got black screen at a time which looked like a GNOME GUI crash and had to reconnect.
> Not sure what was the cause. x11vnc has never done that for an instance.
> But x11vnc is not even a percentage as useful as RustDesk.
> 
> Unfortunately since its a nightly build and that i am very cautious about possible unstable software.
> I have chosen to install version 1.2 nightly on a VM and connected to RPI4 RustDesk through that.
> 
> So i controlled the VM though VNC and then RPI4 through RustDesk on VM.
> Gave some noticeable lag :D
> 
> I also tried testing the keybindings through RustDesk.
> The special characters i know i have problems with on 1.9 work on RustDesk 1.2 on RPI4 as well.
> 
> On the same time that i dont usually use nightly/beta releases on my main systems.
> This is my main Pi and only RPI4 i have.
> So im a bit cautious about what i put on it and do with it.
> 
> With that said.
> Is there anything else in particular that could be useful testing?
> now that it is on there just waiting to be used for something :)
> 
> Am very excited about this beta release.
> This is a way better solution than a lot of other remote solutions out there.
> Its faster, more stable, Supports clipboard and sound and a lot more.
> 
> I am looking very much forward for a full release of 1.2 :)
> 
> Best regards,
> Darkyere

we have noticed the lag and vnc issues on rpi system and we ll find a solution for that, maybe a more light-weight engine or something else. Much appreciatied!

**Comment by Darkyere** [comment]
I have done a bit of some testing.

Since im currently not at home, i was able to make some different scenarios.

----

When i use one of my VM's on my own home's LAN i _can_ connect to RPI4 and the other way around.

But when i am on my parents LAN i _can't_ connect to either the VM's or the RPI4.
This includes both as an client id and Direct IP connection.

----

As a note i am using Wireguard to acces my LAN.
It allows both internet and LAN acces by IP adresses.

----

I am running my own RustDesk server on the RPI4.
I use only allow acces by key.

When inserting RPI4 IP and KEY i get a ready.
This includes RPI4 + VM's on my own LAN and Arch Linux + W10 on the old folks LAN.

I have tried rustdesk on docker both with port and docker network.
And with docker network_mode: host.

It work's internally on my own LAN.
But cant digress from the old folks LAN to my own.

----

I tried as a little test.
I delete my own network settings in RustDesk on RPI4 and W10 at the old Folks.

By that using the public available server, _i could_ actually connect to the RPI4 from my parents network.
Even though i was still using my wireguard connection.

----

Is there anything i can do to help make this work?

**Comment by Darkyere** [comment]
I have been playing a lot around with RustDesk for RPI4 with Ubuntu GNOME.

And i found one thing in particular that seems to be a necessity to make it usable on ARM.

The PI4 is struggling to be able to record the Desktop and send it.
So much its using 33% of a core and still not able to keep up.

From what i can tell. It seems like its trying to record 10FPS (Which is the lowest i can set it to)
But is only available to achieve 1-2 FPS.

Because of this quite often it will freeze for several seconds or until a full refresh has been initiated.
It seems like trying to run with 10 FPS makes the PI4/RustDesk fight to keep up and than get way behind in sending frames and freezes.

I would propose to be able to set the FPS to as low as 1 FPS. To see if one could get a more stable remote controll.
Than trying to do more FPS than what the PI4 is capable of.

In the end having the option to go as low as 1 FPS is a choice people can make if they want to use it.
But having the option would be nice.

I would like to help test a version that allows as low as a single frame. Or what between 1 FPS and 10 FPS that could be usable on the PI4.

**Comment by slimsag** [comment]
@Kingtous I can confirm the rustdesk nightly ARM64 deb package works on the following:

* Rock pi 5 model B
* Armbian OS

Thanks!

**Comment by GeertJohan** [comment]
@Kingtous I've got this working with a Raspberry Pi 4 model B 4GB running Ubuntu 22.04 LTS arm64. I did have to upgrade the controlling machine (amd64, ubuntu) to nightly/1.2.x as well otherwise the connection kept failing. It did get a good connection with working video and input, but connection failed after ~10 seconds. I suspect this may be a protocol incompatibility between 1.1.9 and nightly/1.2.x.

**Comment by rustdesk** [comment]
https://github.com/flutter/flutter/issues/75823
