### ISSUE TITLE
Crash when rustdesk

### ISSUE THREAD

**Issue by Shylock-Hg** [rustdesk/rustdesk#8856]
### Bug Description

```
(base) shylock@localhost:~/Workspace/rustdesk> RUST_BACKTRACE=1 ./target/debug/rustdesk 
[2024-07-27T13:06:44Z INFO  librustdesk::core_main] main start args:[]
[2024-07-27T13:06:44Z INFO  librustdesk::server] DISPLAY=Ok(":0")
[2024-07-27T13:06:44Z INFO  librustdesk::server] XAUTHORITY=Ok("/tmp/xauth_oEEIOm")
[2024-07-27T13:06:44Z INFO  librustdesk::server] server not started (will try to start): Connection refused (os error 111)
[2024-07-27T13:06:44Z INFO  librustdesk::server] DISPLAY=Ok(":0")
[2024-07-27T13:06:44Z INFO  librustdesk::server] XAUTHORITY=Ok("/tmp/xauth_oEEIOm")
[2024-07-27T13:06:44Z INFO  librustdesk::rendezvous_mediator] start rendezvous mediator of rs-ny.rustdesk.com
[2024-07-27T13:06:44Z INFO  librustdesk::common] Testing nat ...
thread 'main' panicked at library/core/src/panicking.rs:220:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
[2024-07-27T13:06:44Z INFO  librustdesk::ipc] Started ipc server at path: /tmp/RustDesk/ipc
[2024-07-27T13:06:44Z INFO  librustdesk::ipc] Started ipc_pa server at path: /tmp/RustDesk/ipc_pa
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:120:5
   3: core::panicking::panic_nounwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:220:5
   4: core::slice::raw::from_raw_parts::precondition_check
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ub_checks.rs:66:21
   5: core::slice::raw::from_raw_parts
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ub_checks.rs:73:17
   6: sciter::value::Value::unpack_from
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/value.rs:563:14
   7: sciter::eventhandler::process_events
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/eventhandler.rs:208:24
   8: sciter::eventhandler::_event_handler_window_proc
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/eventhandler.rs:54:2
   9: _ZN7ext_ctl16on_x_method_callERN4html4viewEPNS0_7elementEPKcPKN4tool5valueEmRS8_
  10: _ZN4html4view20call_behavior_methodEPNS_7elementEPKcPKN4tool5valueEmRS6_
  11: <unknown>
  12: _ZN3tis4SendEPNS_2VMEPNS_13FrameDispatchEi
  13: _ZN3tis4Exec3runEPNS_2VMEb
  14: <unknown>
  15: _ZN3tis14CsCallFunctionEPNS_7CsScopeEmiz
  16: _ZN3tis12CsLoadStreamEPNS_7CsScopeEPNS_6streamES3_i
  17: _ZN3tis9CsIncludeEPNS_7CsScopeEmb
  18: _ZN3tis4Exec3runEPNS_2VMEb
  19: <unknown>
  20: _ZN3tis14CsCallFunctionEPNS_7CsScopeEmiz
  21: _ZN3tis12CsLoadStreamEPNS_7CsScopeEPNS_6streamES3_i
  22: _ZN3tis5xview3runERNS_6streamEN4tool6handleIN4html8documentEEEi
  23: _ZN3tis19load_script_elementEPNS_5xviewEN4tool6handleIN4html8documentEEENS3_INS4_7elementEEE
  24: _ZN3tis5xview11on_load_endEPN4html8documentEb
  25: _ZN4html4view10parse_htmlERNS_7istreamE
  26: _ZN4html4view9load_htmlEN4tool5sliceIhEERKNS1_8string_tIcDsEEj
  27: _ZN4html4view4loadEN4tool6handleINS_7requestEEE
  28: _ZN4html4view8load_urlERKN4tool8string_tIcDsEEb
  29: <unknown>
  30: <unknown>
  31: _Z18SciterLoadFile_apiP10_GtkWidgetPKDs
  32: sciter::host::Host::load_file
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/host.rs:275:3
  33: sciter::window::Window::load_file
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/window.rs:281:3
  34: librustdesk::ui::start
             at ./src/ui.rs:174:5
  35: rustdesk::main
             at ./src/main.rs:35:9
  36: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
Aborted (core dumped)

```

### How to Reproduce

1. Build according guide
2. run  binary directly as `target/debug/rustdesk`

### Expected Behavior

Shouldn't crash.

### Operating system(s) on local side and remote side

Opensuse Tumbleweed -> none

### RustDesk Version(s) on local side and remote side

9f0985c842535a190d6d9d0a098a9c81db112619->none

### Screenshots

```
(base) shylock@localhost:~/Workspace/rustdesk> RUST_BACKTRACE=1 ./target/debug/rustdesk 
[2024-07-27T13:06:44Z INFO  librustdesk::core_main] main start args:[]
[2024-07-27T13:06:44Z INFO  librustdesk::server] DISPLAY=Ok(":0")
[2024-07-27T13:06:44Z INFO  librustdesk::server] XAUTHORITY=Ok("/tmp/xauth_oEEIOm")
[2024-07-27T13:06:44Z INFO  librustdesk::server] server not started (will try to start): Connection refused (os error 111)
[2024-07-27T13:06:44Z INFO  librustdesk::server] DISPLAY=Ok(":0")
[2024-07-27T13:06:44Z INFO  librustdesk::server] XAUTHORITY=Ok("/tmp/xauth_oEEIOm")
[2024-07-27T13:06:44Z INFO  librustdesk::rendezvous_mediator] start rendezvous mediator of rs-ny.rustdesk.com
[2024-07-27T13:06:44Z INFO  librustdesk::common] Testing nat ...
thread 'main' panicked at library/core/src/panicking.rs:220:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
[2024-07-27T13:06:44Z INFO  librustdesk::ipc] Started ipc server at path: /tmp/RustDesk/ipc
[2024-07-27T13:06:44Z INFO  librustdesk::ipc] Started ipc_pa server at path: /tmp/RustDesk/ipc_pa
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:120:5
   3: core::panicking::panic_nounwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:220:5
   4: core::slice::raw::from_raw_parts::precondition_check
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ub_checks.rs:66:21
   5: core::slice::raw::from_raw_parts
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ub_checks.rs:73:17
   6: sciter::value::Value::unpack_from
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/value.rs:563:14
   7: sciter::eventhandler::process_events
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/eventhandler.rs:208:24
   8: sciter::eventhandler::_event_handler_window_proc
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/eventhandler.rs:54:2
   9: _ZN7ext_ctl16on_x_method_callERN4html4viewEPNS0_7elementEPKcPKN4tool5valueEmRS8_
  10: _ZN4html4view20call_behavior_methodEPNS_7elementEPKcPKN4tool5valueEmRS6_
  11: <unknown>
  12: _ZN3tis4SendEPNS_2VMEPNS_13FrameDispatchEi
  13: _ZN3tis4Exec3runEPNS_2VMEb
  14: <unknown>
  15: _ZN3tis14CsCallFunctionEPNS_7CsScopeEmiz
  16: _ZN3tis12CsLoadStreamEPNS_7CsScopeEPNS_6streamES3_i
  17: _ZN3tis9CsIncludeEPNS_7CsScopeEmb
  18: _ZN3tis4Exec3runEPNS_2VMEb
  19: <unknown>
  20: _ZN3tis14CsCallFunctionEPNS_7CsScopeEmiz
  21: _ZN3tis12CsLoadStreamEPNS_7CsScopeEPNS_6streamES3_i
  22: _ZN3tis5xview3runERNS_6streamEN4tool6handleIN4html8documentEEEi
  23: _ZN3tis19load_script_elementEPNS_5xviewEN4tool6handleIN4html8documentEEENS3_INS4_7elementEEE
  24: _ZN3tis5xview11on_load_endEPN4html8documentEb
  25: _ZN4html4view10parse_htmlERNS_7istreamE
  26: _ZN4html4view9load_htmlEN4tool5sliceIhEERKNS1_8string_tIcDsEEj
  27: _ZN4html4view4loadEN4tool6handleINS_7requestEEE
  28: _ZN4html4view8load_urlERKN4tool8string_tIcDsEEb
  29: <unknown>
  30: <unknown>
  31: _Z18SciterLoadFile_apiP10_GtkWidgetPKDs
  32: sciter::host::Host::load_file
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/host.rs:275:3
  33: sciter::window::Window::load_file
             at /home/shylock/.cargo/git/checkouts/rust-sciter-06aa50f9c0fcf3d6/fab913b/src/window.rs:281:3
  34: librustdesk::ui::start
             at ./src/ui.rs:174:5
  35: rustdesk::main
             at ./src/main.rs:35:9
  36: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
Aborted (core dumped)

```

**Comment by fufesou** [comment]
Use rust version `1.75` instead of the latest

**Comment by rustdesk** [comment]
#763
