### ISSUE TITLE
Can't build rustdesk on Linux (error with Scrap and magnum-opus)

### ISSUE THREAD

**Issue by vlashada** [rustdesk/rustdesk#987]
**Describe the bug you encountered:**

When I try running to build rustdesk using `cargo run`, it crashes during the build phase.
...

**What did you expect to happen instead?**

I expected it to build and run
...

**How did you install `RustDesk`?**

I git cloned the github release (dadd667) and tried running the program with cargo

---

**RustDesk version and environment**
`cargo --version -> 1.61.0`
`vcpkg --version -> vcpkg package management program version 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e`
`cargo run`

   ```
   Compiling scrap v0.5.0 (/home/archer/dev/git/rustdesk/libs/scrap)
   Compiling magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86)
   Compiling rustdesk v1.1.10 (/home/archer/dev/git/rustdesk)
error: failed to run custom build command for `magnum-opus v0.4.0 (https://github.com/open-trade/magnum-opus#3c3d0b86)`

Caused by:
  process didn't exit successfully: `/home/archer/dev/git/rustdesk/target/debug/build/magnum-opus-eb0b22ec43ce6f79/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /home/archer/.cargo/git/checkouts/magnum-opus-7580b098b18e2bc5/3c3d0b8/build.rs:7:50
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
     2: core::result::unwrap_failed
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1078:23
     4: build_script_build::find_package
               at ./build.rs:7:22
     5: build_script_build::gen_opus
               at ./build.rs:70:20
     6: build_script_build::main
               at ./build.rs:87:5
     7: core::ops::function::FnOnce::call_once
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `scrap v0.5.0 (/home/archer/dev/git/rustdesk/libs/scrap)`

Caused by:
  process didn't exit successfully: `/home/archer/dev/git/rustdesk/target/debug/build/scrap-7fdadb4c7c4c0c81/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', libs/scrap/build.rs:7:50
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
     2: core::result::unwrap_failed
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1078:23
     4: build_script_build::find_package
               at ./build.rs:7:22
     5: build_script_build::main
               at ./build.rs:97:5
     6: core::ops::function::FnOnce::call_once
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rustdesk** [comment]
#763
